dna = 'TTTTAATTCTTTGAGAATTCAGATACGATCGCCACACGTGGGAATCAAGATATTTCAGGAGATAACTATGTTAGGTCCGCTGTACCGAGTGACGACGATTTTGATGGCCGCACGAAATGTTCATATCCTGAAGTTTTGGGTAGCAGAATTTAGGTTGGAGTTATAACGCTTCTACGTTACTAGGTGCGATGATCAGACACAAAGAATCCCATGACTTAGCAACCTGAGACACAGGACAGTGCTTACCTTACCGGTGAGGGCGGGCACAGTGCGCATTGATCGTGGATGTAGGCAGACGTAGCTACTACTTCCGCCAGCCATCTGTTGTTTTAGCGTGCGCTATGCGTAAAATCCTCAATACGCGCTATCATAAATATCCGCATATGCGCTAGTCCTACTAAGGCTTGCTCCTATTCCTACGATCTTCGTGCTCACTGTCAGTTAGCTCTAGATATGCCTACCCCTGCGTTCTCGCTCAACAGCAGGTTAAGGTTGAGTTTATGGGATGCTGACGTGTGCGGAGGGAGCTACCCCGTGAGTTAACTTATGGCCAAGTGCTCAGTGCCCGCTTGGGGCACGAAAGAATATGAATAGTAGCCCAATCGAAAGCCCTGAGATTAATAGCGTGCGGAAGTCTCGCGCCTCCCTACGCTTAATCGTTAGTTGTACCTGCCTCGTTCCTCATACATAACGAGGCAGAATAAGGGGTCGGTGCCCGACTAACGGGCATTCTCTATGGCCATTGAACGACCCGATGTTTAACTACTAGTTCCTTCCGGGATAATCTGGTTGAGTGGAGTCCCGGTCACGCGCTCGACGAACCCTGCGAGAAGGTAGAGTATTATCTCCCTTGATGTTAATCCAGTAATCACTTCTCATCGTAATCATTGGTAAAAGGCAGGCTGGTCTATTCTACCCAACACCAGAGGGGGCGGTACATAATCCTGGTTTGTTTACAATACCACAATTCCACCTTGATGTGGG'
listdna = list(dna)
output = list(dna)

i = 0

while i < len(listdna):
    if listdna[i] == 'A':
        output[i] = 'T'
        i = i+1
    elif listdna[i] == 'T':
        output[i] = 'A'
        i = i+1
    elif listdna[i] == 'C':
        output[i] = 'G'
        i = i+1
    else:
        output[i] = 'C'
        i = i+1

output.reverse()
string = ''.join(output)
print string 
