dna = 'ACTAAAGAGGTAATCCCTCAATCTCGCATTCCCAGGCCACTCTGATACGGTGAACTGAGGGGGGTCTTGTCGAAGGGTTGCGCAAACTTTAATTGCGCAGAACGGTTTTGATATGAAGACCGTCGAACGAGCTGGAGTGAGAATAAGGCCGGTCAGCGTCAAGAGGAACCTACCTGTAACAACAGGAGATCGAAAATATGACTAGTTGGGACCCACAATTTTAATGGGTGCGGGAGTCAGACCGGAACAGGGGCTATAATATAAGACGACCTCAATTTTACAAGTGCAAACAACAAGTACACTAAACGATTTAAGGACCAATTCTTTAGGCTATCGTTCACGTTGTTCCGTCTTTTGGGAGTATAAGGACCGGATGCAACTATAGGCATTCGAAACCCGGTAAAAAACAGTGCGGACGCGGACTTAGCAGCGCAACCCGCCTGTAAATCAAGCCTTCACGGGTCCCCAGATTGAAGAGGAGCAATAGCAACCGGGCCACCCGCCTCTCCAGCCCCTTACCGGAAGCTCGTTCCGATGTGCCCGGCCCTCTTTCCTCGCGTTGCCTCTCTGTAGCGGCACTTTTGCCTGAAACCCAGCAGGGCAAGCTATCACGGTCGTGTACAAAAGATGGGCCTGTGCTTCCCGAAGCTGAGTTACTCTGACTGCGATCGCTGGTGCTGCCCTTAATTCCCCCTTGAATGTACTCTCATACCACACTCACCCTCATTTGGGTCCGCTTATATTCTATAGTATGATTGGTATTAGGCCAGTTGTGAGGGGTTGATAACGCCATTCTCCCTAATGCCCATTTTCTGTTATGGATTTACTGTGTGTAAAAATAAAAATCGTAAGATCGTGCAACTGCCCTGGCTCAACCTCGCGCATGACCGAGGGTTGGGCTTCTCAAACTGAGTAGTTCCTATGTGACTAAACGTGCGCGGCCCTGA'
listme = list(dna)

i = 0
A = 0
G = 0
T = 0
C = 0

while i < len(listme):
    if listme[i] == 'A':
        A = A+1
        i = i+1
    elif listme[i] == 'G':
        G = G+1
        i = i+1
    elif listme[i] == 'T':
        T = T+1
        i = i+1
    elif listme[i] == 'C':
        C = C+1
        i=i+1
    else:
        i = i

print A,C,G,T
