string = 'CTCCAGAACTGCCCAAAGTCGATTAAATGAACTCAGGACATATTCCCCGCTTGCAAATTA\
ATTCGCAGTGGTAAGCGCACAGTCGGCTTGTACGGGATCATCAGTGTGGTTGCTCAACTC\
GTACCGCGTAACACTGCCATGCATAGGGAAAGCCGGGAGTTCGCTTCAACGATTTGTCGG\
GAGGCGCCTATACTCACGACTTGTGACCTGGAGAACCTGCGCTGTTGTCTGAACATGTAG\
CCAACTCTTTCGCAAGCGGGTTATTAGGCCGAGTCCTGTGCCCCCTAGAGCGACCGGTCC\
CCGGAGGTGGTCCCGCATGTACTGCTTCATGCTTAGGTAGGTTGGTCACCGAGCGGCGCA\
GTAAAAATCCGGGTCGGATTAGCGATGCTATCTCCGCAGGGCTGATGACGTCCCCATAGA\
AACACGCGGTCAGTGTGACATGGGCCGCGGGAGTGTGCCCCGCCTCACCGCCCAGATAAA\
GCTGTCTTGACACGTGGGCCCTCCACGGCTATACTTGCGGTGCCATTACAAGCGTATCGG\
CCCGTGAGGGCAGGTGCCTGAAAAAACGTATGAGCTACGTATTGAACGATCTAGCAAGAC\
CTGGCCGCACTCTGTTGTCTGAGGCGCAGTAGCTGTCTAGCGCGAAAAGATAGAACCATT\
GGCTGGCTTTGCGTATTGGGGATATGCTACATGGTGAGCAGTGCTTTTCGCGGCGTCTGT\
ATGTCTGGACCAATCTTCCGATGGTCTGGGGTAGATTAACGAGTCATCATTTTATACGGA\
ACGTCGGTTCCTCTATCCGGAGATCCTCCCGCTCATGCCTTATGTCCCCCGGACCTAACC\
ACAGAGAACATGG'

listdna = list(string)
print string

i = 0
num = 0

while i < len(listdna):
    if listdna[i] == 'C' or listdna[i] == 'G':
        num = num + 1
        i = i + 1
    else:
        i = i + 1

print float(num)/len(listdna)*100
    

