dna = 'AGCCAGACAGGTCCATGCGCTTCTGTATTGCTTAGACGTGCCCAACCTGCACCACTATCGTTCTATGGTACCGTTTCGAGTGGGAGCCACACCTGGCTTCTAAGGATTGCTAAGCAAAAAATAGAATGCCCCCTAGAGATGTACCGAGCATTTGCTCGTGCTAAACAGGCTACATGCATAGAACCTGGATCTAGGCACGTTGAAGCGCCGCCCGCGATTGGTTTCGCGCGGGTCAAAGTTATTGGGCAATCCGTGTACACGTCTTACGGGCGTTCTTCTGACTAACGGAATAACACACATCAAGCGGAGTAGTGTTAGACATCCATGTGAGTCGATGGCGGGTTCATTCTGTTGTCAACAACTTGTCATCGCTCAGCGGCGAACAGATTTGGGTACCGGATCTGAGCATAGGCTTTTTACGGGAGTTTTAACATCAAAGTATTTGTCATTCCCTATGGCTCGTGGGTCGTCGCTAGCCTTCAGTCTGCATGTTTTTGTTCTCGTAATATCCGTCTTTACGTCGATTCTACAGTCGCATAGGTGTGTTCGCAGACTTCGAGACTCTCTCGCCCGCCGTTAAGGATAACAAGGTCCCGATTCGTGCCGAACACCGATACAGTAAATGACGTAATGTCCCCCTGTTAGCTTGCTGTTAGGCGTATTAACAAGATTGCGATGGTAGTCTCAACTGCGCCTATTAAATCTAGGCCAAATCCCACAGGACCAACCAATTCTGTCGCGCTCCGTCATTAGTTGATCTCAACTTATTACAGCCGGGCCGACGATTTCCAATCGTTTGGCGTGTCACGCATTAGTATCAGACCAAATCAGTACAAAAGCCCCGTGGTTCGATGGCATGCAATAGGAGATGCGGGATACGGTTAATGAGCAGTTGTAGGTTTTTAGTCAGCAACATAATTTGAGAT'
listDNA = list(dna)
listRNA = list(dna)

i = 0

while i < len(listDNA):
    if listDNA[i] == 'T':
        listRNA[i] = 'U'
        i = i+1
    else:
        listRNA[i] = listDNA[i]
        i = i+1

string = ''.join(listRNA)
print string
